var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                xxxxxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x    k   k    x   x       k     k    x     x      xxx  k     x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                      ooo                                                       ",
   "                     oxxx                                                       ",
   "                     xx!xx                                                      ",
   "                     x!!!x                                                      ",
   "                   o xx!xx                                                      ",
   "                 xxx  xvx                                                       ",
   "                                                                  xxxx      xx  ",
   "                                                                             x  ",
   "                  o                                       xx                 x  ",
   "             xxxx  o                      ooo                    x           x  ",
   "                    o                                            x           x  ",
   "  x  @               o   k     oo      k      x   k        oo   kx   oo   k  x  ",
   "  xxxxxxxxxxxx   |   xxxxxx    xx    xxxx     xxxxx        xxxxxxx   xxxxxxxxx  ",
   "             x!!!!!!!x    x         |x   x        x       |x                    ",
   "              x!!!!!x     x!!!!!!!!!!x            xxxx!!!!!x                    ",
   "               x!!!x      x!!!!!!!!!!x               x!!!!!x                    ",
   "                x!x       xxxxxxxxxxxx               xxxxxxx                    ",
   "                xxx                                                             ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                           ooo                                  ",
   "                                           xxx                                  ",
   "                                         xx!!!xx                                ",
   "                                        x!!!!!!!x       x   k   x               ",
   "  o  o       o             k   o        x!!!!!!!x           k                   ",
   "             x            xxxxxx         x!!!!!x         xxxxxxx                ",
   "  o  o       x                            xxvxx                             xx  ",
   "  xxxxx      x                                                               x  ",
   "  x          x        xxx                                                    x  ",
   "  x          x                   k                                           x  ",
   "  x          x                                                               x  ",
   "  x  @     k x     k     k                  |                k   xxxxx   k   x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx          o  k              xxxxxxx   xxxxxxxxx  ",
   "                              x|        xxxxxxxxx         |x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "]
  ["                                                       ooooo                                      ",
   "                                                       ooooo                                      ",
   "                                                    xxxxxxxx                                      ",
   "                                                    x!!!!!!x                                      ",
   "                               o                     x!!!!!x                                      ",
   "                               o                      x!!!!x                                      ",
   "                               o            xxx        x!!!x                                      ",
   "                          k                             xvxx                                      ",
   "   o               k                             o                              o                 ",
   "                                             k   o                            k o                 ",
   "   o         x                xx            xxxxxx                         xxxxxxx                ",
   "             x        o       xx                                            |    xx          oxx  ",
   "  xxxxx      x        o       xx                                                  xx         o x  ",
   "  x          x        o       xx                              k                              o x  ",
   "  x          x        o       xx        k         o o                                o       o x  ",
   "  x          x      xxxxx     xx                                                     o       o x  ",
   "  x  @     k x                xxo       o  k                    o              k   xxxxx   k o x  ",
   "  xxxxxxxxxxxx|              |xxxxxxxxxxxxxxxxx            k    o            xxxxxxx   xxxxxxxxx  ",
   "             x!!!!!!!!!!!!!!!!x               x           |xxxxxxx           x                    ",
   "             x!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "             x!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "             x!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "             x!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "             xxxxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
